### ISSUE TITLE
Add support for Angular 9

### ISSUE THREAD

**Issue by IshanRatnapala** [ivylaboratory/angular-carousel#17]
Getting an error `Cannot find module 'angular-responsive-carousel'` when installed on a Angular 9 project.

I think it's caused because of the peer deps.
`
"peerDependencies": {
    "@angular/common": "~7.2.0",
    "@angular/core": "~7.2.0"
  },
`

**Comment by drozhzhin-n-e** [comment]
@IshanRatnapala Thank. Try to install the latest version.
