### ISSUE TITLE
vertical scrolling

### ISSUE THREAD

**Issue by flyingcodelabs** [ivylaboratory/angular-carousel#19]
It is not possible to verticly scroll ( on mobile ) on the picture.
Is it possible to fix this behaviour?

Horizontal swipe moves the carousel, but when scrolling down, I should be able to scroll to the bottom of the page. 
When the images take most of the real-estate this is not good for mobile.

Thank you

**Comment by drozhzhin-n-e** [comment]
@flyingcodelabs I fixed this in version 1.3.10
