### ISSUE TITLE
carousel.currentCellIndex undefined when click.

### ISSUE THREAD

**Issue by trylled** [ivylaboratory/angular-carousel#22]
Error when clicking on image/carousel  

![image](https://user-images.githubusercontent.com/12077462/90837683-571e9900-e385-11ea-9f47-2e2514fbceef.png)

error points here: https://github.com/ivylaboratory/angular-carousel/blob/master/src/app/carousel/carousel.component.ts#L274

Possible cause: I checked https://github.com/ivylaboratory/angular-carousel/blob/master/src/app/carousel/carousel.ts but can't find currentCellIndex property.

**Comment by drozhzhin-n-e** [comment]
@trylled Hey. I fixed this in version 1.3.11.
