### ISSUE TITLE
error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by vascocandeias** [ivylaboratory/angular-carousel#25]
I have just started using this package and when building the website, the following errors are thrown:

![image](https://user-images.githubusercontent.com/42552118/91909469-2869c200-eca5-11ea-95b7-af52b53c7e60.png)

From what I've searched, this could be solved by updating Typescript to its latest version. However, I cannot do that since I am running Angular 8. While I plan to upgrade in the near future, is there any temporary fix for the package I could try?

Thanks!

**Comment by drozhzhin-n-e** [comment]
Hey. Try to grab the source code from the repository and copy it to your project. Import the library like any other module inside your application.

**Comment by vascocandeias** [comment]
I ended up upgrading the whole project to Angular 10, marking it as solved.
