### ISSUE TITLE
events not working in 1.3.11 version

### ISSUE THREAD

**Issue by mohsenolaiki** [ivylaboratory/angular-carousel#33]
hi there
thanks for this great component.

it seems that "events" not working anymore after 1.3.10 version in npm
it's working in 1.3.10 . but in 1.3.11 and newer versions not.

thanks.

**Comment by tradeouts** [comment]
I'm having the same problem

**Comment by IslaMurtazaev** [comment]
Having the same issue in 2.0.2
Is there any workaround to get on change event emitter?

**Comment by alexisqc92** [comment]
Did anyone was able to get the event emitter?

**Comment by drozhzhin-n-e** [comment]
Events have been moved to the Pro version.
