### ISSUE TITLE
[Question] How to style the dots with a different color? 

### ISSUE THREAD

**Issue by Voldiemert** [ivylaboratory/angular-carousel#47]
I'm using this carousel, and trying to make the dots grey instead of white, but I'm not having any success doing so.

I've tried to target them with css by targeting the class .carousel-dot-active, .carousel-dot, .carousel-cells.carousel-dot-active, and .carousel-cells.carousel-dot. 

I haven't had any luck changing the colors with this method.

Any help figuring this out, or being told it's not possible would be appreciated.

**Comment by demetrio812** [comment]
Hello, I've done it in this way:

```
::ng-deep .carousel {
  .carousel-dot {
    border: 1px solid #777 !important;
  }

  .carousel-dot-active {
    background-color: #777 !important;;
  }

  .carousel-arrow {
    background-color: #777 !important;
  }

}
```

**Comment by Voldiemert** [comment]
> Hello, I've done it in this way:
> 
> ```
> ::ng-deep .carousel {
>   .carousel-dot {
>     border: 1px solid #777 !important;
>   }
> 
>   .carousel-dot-active {
>     background-color: #777 !important;;
>   }
> 
>   .carousel-arrow {
>     background-color: #777 !important;
>   }
> 
> }
> ```
> 
> Basically you need to use ::ng-deep in my case I've set the `class="carousel"` to the component so I can control which carousel gets the new colours

I ended up doing the same thing. I tried to avoid it because ::ng-deep is deprecated, but it was the only thing I could get to work. If ::ng-deep ends up being removed in the future without a replacement, I'll deal with that issue then.

**Comment by drozhzhin-n-e** [comment]
You can override the color through the global stylesheet.

**Comment by muhaym** [comment]
Can dots position be changed? @drozhzhin-n-e

**Comment by michcio1234** [comment]
>You can override the color through the global stylesheet.

@drozhzhin-n-e would you mind giving a short short example? Or can I find such an example somewhere in this repo? Thank you.
