### ISSUE TITLE
(events)="handleCarouselEvents($event);" - How do I access just the click event for the imageIndex and not the other events?

### ISSUE THREAD

**Issue by Apperfect** [ivylaboratory/angular-carousel#56]

**Comment by drozhzhin-n-e** [comment]
```
handleCarouselEvents(event) {
	if (event.name === "click") {
		...
	}
}
```

Perhaps I do not quite understand what you mean

**Comment by pafontana** [comment]
Hi, I'm having a problem with the event , when i do click on the carousel-cell, doesn't call to handleCarouselEvents(event)

this is my html code


    <carousel class="carousel"
    (events)="handleCarouselEvents($event)" 
    [cellsToShow]="2"
    [arrowsOutside]="true"
    >        
      <div class="carousel-cell" > 
        <div class="option"> 
          <img class="imgCell"  src="..."></div>
          <span>...</span>
      </div>
      <div class="carousel-cell">
        <div class="option" >
          <img class="imgCell"  src="..."></div>
          <span>...</span>
        </div>
      </div>
    </carousel>
  </div>

there is/are something wrong?

**Comment by yasmanycruz79** [comment]
Same problem

**Comment by drozhzhin-n-e** [comment]
Please note that events are only available in the Pro version.
