### ISSUE TITLE
issue in cellwidth

### ISSUE THREAD

**Issue by sincy123** [ivylaboratory/angular-carousel#65]
I want celltoShow=5 in large devices and celltoShow=2 in small/medium devices. How can I implement that?

**Comment by northern1317** [comment]
> I want celltoShow=5 in large devices and celltoShow=2 in small/medium devices. How can I implement that?

Hello, i make like that:
HTML:
`  <carousel  [cellsToShow]="isMobile ? 1 : 3" ` 
TS:
`
 isMobile: boolean;

 checkDeviceViewPort = () => {
    if (window.screen.width < 768) {
      this.isMobile = true;
    } else {
      this.isMobile = false;
    }
    this.getActiveItems();
  }`
