### ISSUE TITLE
Carousel Width 0px

### ISSUE THREAD

**Issue by stijdoyle** [ivylaboratory/angular-carousel#66]
I've downloaded pro v 2.0.4.

I'm using HTML content, and for some reason my `<carousel>` element style attribute is always explicitly set to `width: 0px;`. I have tried:

1. styling the `carousel` element explicity:
```
<carousel style="width: 100%;">
```

2. styling the `carousel` element with scss:
```
carousel.my-carousel {
  width: 100%;
}
```

3. providing a width input to the component
```
<carousel [width]="400">
```

No matter what I do, the width is always set, at the attribute level, to 0px in the browser.
From the browser inspector:
```
<carousel _ngcontent-gxh-c153="" class="ng-tns-c153-0 carousel" _nghost-gxh-c151="" style="height: 200px; width: 0px;"></carousel>
```

Is the carousel not able to work with elements loaded from an `*ngFor`?
My source:
```
<carousel>
  <my-html-component  class="carousel-cell" *ngFor="comp in myComponents"/>
</carousel>
```

**Comment by neeraj2018** [comment]
@stijdoyle were you able to fix this? I am also facing the same issue.
