### ISSUE TITLE
Module name on Documentation

### ISSUE THREAD

**Issue by renamoo** [ivylaboratory/angular-carousel#7]
Hi, thank you for publishing carousel library! I like your demo.
```
 import {IvyCarouselModule} from 'angular-responsive-carousel';

  @NgModule({
      imports: [IvyCarouselModule]
  })
```
I installed the latest version this morning and I could not import module like above in README.  
I guess followings are correct.
```
 import {CarouselModule} from 'angular-responsive-carousel';

  @NgModule({
      imports: [CarouselModule]
  })
```
(Sorry, I cannot submit PRs to the repository without license due to my company's rule)

**Comment by drozhzhin-n-e** [comment]
@renamoo Thank you for informing! I will fix it soon.

**Comment by FrancescoPaiola** [comment]
I have the same problem. But both modules (IvyCarouselModule and CarouselModule) are not found.
Error message:
```
./src/app/app.module.ts
Module not found: Error: Can't resolve 'angular-responsive-carousel' in '/code/src/app'
```

**Comment by drozhzhin-n-e** [comment]
@FrancescoPaiola which version of Angular are you using?
