### ISSUE TITLE
Animations on cell elements causing issues

### ISSUE THREAD

**Issue by cwqt** [ivylaboratory/angular-carousel#73]
To preface I'm putting html (not images) elements inside the carousel

If an element within the `carousel-cells` element has a `:hover` style that performs some kind of transformation, it causes `handleTransitionendCellContainer` to trigger on mouseover, which in turn makes the carousel move to the next/previous position erroneously
 
![image](https://user-images.githubusercontent.com/61694629/116095656-861da500-a6a0-11eb-95a2-2a56cced54b8.png)

Quick fix, only handle events if it came from the `carousel-cells` element

```ts
  handleTransitionendCellContainer(event) {
    if (event.target['className'] !== 'carousel-cells') return;
```

**Comment by drozhzhin-n-e** [comment]
Thank you!
