### ISSUE TITLE
Remove event.preventDefault() "Unable to preventDefault inside passive event listener invocation"

### ISSUE THREAD

**Issue by rolodev1** [ivylaboratory/angular-carousel#75]
Hi.

In my angular project when I scroll carousel horizontally it shows me an error which is: "Unable to preventDefault inside passive event listener invocation.", I checked the root file of the library and I commented on line 1448 and the error stopped appearing in the console.

I ask that you please comment on this line to avoid excessive messages on the console.

PD: English is not my native language.

![image](https://user-images.githubusercontent.com/63069370/116901010-098a4980-abff-11eb-9932-14bfc57c8f81.png)

**Comment by drozhzhin-n-e** [comment]
Hi. You are right, this can be removed.
