### ISSUE TITLE
The Pro version doesn't WORK!

### ISSUE THREAD

**Issue by S1nPur1ty** [ivylaboratory/angular-carousel#82]
I get many issues with the PRO version that I just bought. Can you please fix issues like these ASAP:

<img width="1023" alt="Screenshot 2021-05-27 at 16 13 52" src="https://user-images.githubusercontent.com/61484213/119790456-88c12380-bf06-11eb-9002-4237485ee414.png">

<img width="687" alt="Screenshot 2021-05-27 at 16 14 06" src="https://user-images.githubusercontent.com/61484213/119790498-91195e80-bf06-11eb-8158-f0c030cddc89.png">

I am using ivyсarousel_pro_2.0.4

**Comment by drozhzhin-n-e** [comment]
This is due to the active property "strict": true in tsconfig.json. This will be fixed in a future release

**Comment by drozhzhin-n-e** [comment]
This has been fixed in version 2.1.0
