### ISSUE TITLE
Tutorial is outdated!

### ISSUE THREAD

**Issue by S1nPur1ty** [ivylaboratory/angular-carousel#83]
I have been trying to get the carousel element by using the code samples you show, but none of them work so far. I have to say that it frustrates me, because I am in a hurry. Can you please take a look and fix this problem if possible:

```
import { Component, ViewChildren, OnInit } from '@angular/core';
import { CarouselComponent } from 'angular-responsive-carousel/lib/carousel.component';

@Component({
  selector: 'app-roadmap',
  templateUrl: './roadmap.component.html',
  styleUrls: ['./roadmap.component.scss']
})
export class RoadmapComponent implements OnInit {

  @ViewChildren(CarouselComponent) carouselComponent;

  myCarousel: CarouselComponent;

  next() {
      this.myCarousel.next();
  }

  previous() {
      this.myCarousel.prev();
  }

  ngAfterViewInit() {
    this.myCarousel = this.carouselComponent.find((elem:any) => elem.id === "myCarousel");
  }

  ngOnInit(): void {
  }

}
```

Error: ./src/app/components/landing/roadmap/roadmap.component.ts
Module not found: Error: Can't resolve 'angular-responsive-carousel/lib/carousel.component' in '/Users/logan/Development/angular/xxx/src/app/components/landing/roadmap'

**Comment by drozhzhin-n-e** [comment]
Hello. Let's find out exactly where the problem started. Can you give me a link where exactly did you get this sample code? The error indicates a problem with the import of the carousel module.

**Comment by drozhzhin-n-e** [comment]
I found. This example is from the repository. You are right, it is outdated.
